/*****************************************************************************
	disasm_op.c	- Disassembler/trace table based calls

	Copyright (C) 1996, 1997, 2014, 2018, by Chet Simpson.

	This file is distributed under the MIT License. See notice at the end
	of this file.

*****************************************************************************/
#include <stdio.h>
#include "disasm.h"

Opcode optable[] =
{
	{"neg",		2,	DisasmDirect,			TraceGeneric,			0x00},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x01},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x02},
	{"com",		2,	DisasmDirect,			TraceGeneric,			0x03},
	{"lsr",		2,	DisasmDirect,			TraceGeneric,			0x04},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x05},
	{"ror",		2,	DisasmDirect,			TraceGeneric,			0x06},
	{"asr",		2,	DisasmDirect,			TraceGeneric,			0x07},
	{"lsl",		2,	DisasmDirect,			TraceGeneric,			0x08},
	{"ror",		2,	DisasmDirect,			TraceGeneric,			0x09},
	{"dec",		2,	DisasmDirect,			TraceGeneric,			0x0a},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x0b},
	{"inc",		2,	DisasmDirect,			TraceGeneric,			0x0c},
	{"tst",		2,	DisasmDirect,			TraceGeneric,			0x0d},
	{"jmp",		2,	DisasmDirect,			TraceGeneric,			0x0e},
	{"clr",		2,	DisasmDirect,			TraceGeneric,			0x0f},
	
	{"PAGE10",	1,	DisasmPage10,			TracePage10,			0x10},
	{"PAGE11",	1,	DisasmPage11,			TracePage11,			0x11},
	{"nop",		1,	DisasmInherent,			TraceGeneric,			0x12},
	{"sync",	1,	DisasmInherent,			TraceGeneric,			0x13},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x14},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x15},
	{"lbra",	3,	DisasmRelativeLong,		TraceRelativeJumpLong,	0x16},
	{"lbsr",	3,	DisasmRelativeLong,		TraceRelativeLong,		0x17},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x18},
	{"daa",		1,	DisasmInherent,			TraceGeneric,			0x19},
	{"orcc",	2,	DisasmImmediate,		TraceGeneric,			0x1a},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x1b},
	{"andcc",	2,	DisasmImmediate,		TraceGeneric,			0x1c},
	{"sex",		1,	DisasmInherent,			TraceGeneric,			0x1d},
	{"exg",		2,	DisasmRegToRegOp,		TraceGeneric,			0x1e},
	{"tfr",		2,	DisasmRegToRegOp,		TraceGeneric,			0x1f},
	
	{"bra",		2,	DisasmRelative,			TraceRelativeJump,		0x20},
	{"brn",		2,	DisasmRelative,			TraceRelative,			0x21},
	{"bhi",		2,	DisasmRelative,			TraceRelative,			0x22},
	{"bls",		2,	DisasmRelative,			TraceRelative,			0x23},
	{"bcc",		2,	DisasmRelative,			TraceRelative,			0x24},
	{"bcs",		2,	DisasmRelative,			TraceRelative,			0x25},
	{"bne",		2,	DisasmRelative,			TraceRelative,			0x26},
	{"beq",		2,	DisasmRelative,			TraceRelative,			0x27},
	{"bvc",		2,	DisasmRelative,			TraceRelative,			0x28},
	{"bvs",		2,	DisasmRelative,			TraceRelative,			0x29},
	{"bpl",		2,	DisasmRelative,			TraceRelative,			0x2a},
	{"bmi",		2,	DisasmRelative,			TraceRelative,			0x2b},
	{"bge",		2,	DisasmRelative,			TraceRelative,			0x2c},
	{"blt",		2,	DisasmRelative,			TraceRelative,			0x2d},
	{"bgt",		2,	DisasmRelative,			TraceRelative,			0x2e},
	{"ble",		2,	DisasmRelative,			TraceRelative,			0x2f},
	
	{"leax",	2,	DisasmIndexed,			TraceIndexed,			0x30},
	{"leay",	2,	DisasmIndexed,			TraceIndexed,			0x31},
	{"leas",	2,	DisasmIndexed,			TraceIndexed,			0x32},
	{"leau",	2,	DisasmIndexed,			TraceIndexed,			0x33},
	{"pshs",	2,	DisasmSystemStackOp,	TraceGeneric,			0x34},
	{"puls",	2,	DisasmSystemStackOp,	TracePullStack,			0x35},
	{"pshu",	2,	DisasmUserStackOp,		TraceGeneric,			0x36},
	{"pulu",	2,	DisasmUserStackOp,		TracePullStack,			0x37},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x38},
	{"rts",		1,	DisasmInherent,			TraceReturn,			0x39},
	{"abx",		1,	DisasmInherent,			TraceGeneric,			0x3a},
	{"rti",		1,	DisasmInherent,			TraceGeneric,			0x3b},
	{"cwai",	2,	DisasmInherent,			TraceGeneric,			0x3c},
	{"mul",		1,	DisasmInherent,			TraceGeneric,			0x3d},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x3e},
	{"swi",		1,	DisasmInherent,			TraceGeneric,			0x3f},
	
	{"nega",	1,	DisasmInherent,			TraceGeneric,			0x40},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x41},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x42},
	{"coma",	1,	DisasmInherent,			TraceGeneric,			0x43},
	{"lsra",	1,	DisasmInherent,			TraceGeneric,			0x44},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x45},
	{"rora",	1,	DisasmInherent,			TraceGeneric,			0x46},
	{"asra",	1,	DisasmInherent,			TraceGeneric,			0x47},
	{"lsla",	1,	DisasmInherent,			TraceGeneric,			0x48},
	{"rola",	1,	DisasmInherent,			TraceGeneric,			0x49},
	{"deca",	1,	DisasmInherent,			TraceGeneric,			0x4a},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x4b},
	{"inca",	1,	DisasmInherent,			TraceGeneric,			0x4c},
	{"tsta",	1,	DisasmInherent,			TraceGeneric,			0x4d},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x4e},
	{"clra",	1,	DisasmInherent,			TraceGeneric,			0x4f},
	
	{"negb",	1,	DisasmInherent,			TraceGeneric,			0x50},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x51},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x52},
	{"comb",	1,	DisasmInherent,			TraceGeneric,			0x53},
	{"lsrb",	1,	DisasmInherent,			TraceGeneric,			0x54},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x55},
	{"rorb",	1,	DisasmInherent,			TraceGeneric,			0x56},
	{"asrb",	1,	DisasmInherent,			TraceGeneric,			0x57},
	{"lslb",	1,	DisasmInherent,			TraceGeneric,			0x58},
	{"rolb",	1,	DisasmInherent,			TraceGeneric,			0x59},
	{"decb",	1,	DisasmInherent,			TraceGeneric,			0x5a},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x5b},
	{"incb",	1,	DisasmInherent,			TraceGeneric,			0x5c},
	{"tstb",	1,	DisasmInherent,			TraceGeneric,			0x5d},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x5e},
	{"clrb",	1,	DisasmInherent,			TraceGeneric,			0x5f},
	
	{"neg",		2,	DisasmIndexed,			TraceIndexed,			0x60},
	{NULL,		2,	DisasmIllegal,			TraceGeneric,			0x61},
	{NULL,		2,	DisasmIllegal,			TraceGeneric,			0x62},
	{"com",		2,	DisasmIndexed,			TraceIndexed,			0x63},
	{"lsr",		2,	DisasmIndexed,			TraceIndexed,			0x64},
	{NULL,		2,	DisasmIndexed,			TraceIndexed,			0x65},
	{"ror",		2,	DisasmIndexed,			TraceIndexed,			0x66},
	{"asr",		2,	DisasmIndexed,			TraceIndexed,			0x67},
	{"lsl",		2,	DisasmIndexed,			TraceIndexed,			0x68},
	{"rol",		2,	DisasmIndexed,			TraceIndexed,			0x69},
	{"dec",		2,	DisasmIndexed,			TraceIndexed,			0x6a},
	{NULL,		2,	DisasmIllegal,			TraceGeneric,			0x6b},
	{"inc",		2,	DisasmIndexed,			TraceIndexed,			0x6c},
	{"tst",		2,	DisasmIndexed,			TraceIndexed,			0x6d},
	{"jmp",		2,	DisasmIndexed,			TraceIndexed,			0x6e},
	{"clr",		2,	DisasmIndexed,			TraceIndexed,			0x6f},
	
	{"neg",		3,	DisasmExtended,			TraceGeneric,			0x70},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x71},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x72},
	{"com",		3,	DisasmExtended,			TraceGeneric,			0x73},
	{"lsr",		3,	DisasmExtended,			TraceGeneric,			0x74},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x75},
	{"ror",		3,	DisasmExtended,			TraceGeneric,			0x76},
	{"asr",		3,	DisasmExtended,			TraceGeneric,			0x77},
	{"lsl",		3,	DisasmExtended,			TraceGeneric,			0x78},
	{"rol",		3,	DisasmExtended,			TraceGeneric,			0x79},
	{"dec",		3,	DisasmExtended,			TraceGeneric,			0x7a},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0x7b},
	{"inc",		3,	DisasmExtended,			TraceGeneric,			0x7c},
	{"tst",		3,	DisasmExtended,			TraceGeneric,			0x7d},
	{"jmp",		3,	DisasmExtended,			TraceGeneric,			0x7e},
	{"clr",		3,	DisasmExtended,			TraceGeneric,			0x7f},
	
	{"suba",	2,	DisasmImmediate,		TraceGeneric,			0x80},
	{"cmpa",	2,	DisasmImmediate,		TraceGeneric,			0x81},
	{"sbca",	2,	DisasmImmediate,		TraceGeneric,			0x82},
	{"subd",	3,	DisasmImmediateLong,	TraceGeneric,			0x83},
	{"anda",	2,	DisasmImmediate,		TraceGeneric,			0x84},
	{"bita",	2,	DisasmImmediate,		TraceGeneric,			0x85},
	{"lda",		2,	DisasmImmediate,		TraceGeneric,			0x86},
	{NULL,		2,	DisasmIllegal,			TraceGeneric,			0x87},
	{"eora",	2,	DisasmImmediate,		TraceGeneric,			0x88},
	{"adca",	2,	DisasmImmediate,		TraceGeneric,			0x89},
	{"ora",		2,	DisasmImmediate,		TraceGeneric,			0x8a},
	{"adda",	2,	DisasmImmediate,		TraceGeneric,			0x8b},
	{"cmpx",	3,	DisasmImmediateLong,	TraceGeneric,			0x8c},
	{"bsr",		2,	DisasmRelative,			TraceRelative,			0x8d},
	{"ldx",		3,	DisasmImmediateLong,	TraceGeneric,			0x8e},
	{NULL,		2,	DisasmIllegal,			TraceGeneric,			0x8f},
	
	{"suba",	2,	DisasmDirect,			TraceGeneric,			0x90},
	{"cmpa",	2,	DisasmDirect,			TraceGeneric,			0x91},
	{"sbca",	2,	DisasmDirect,			TraceGeneric,			0x92},
	{"subd",	2,	DisasmDirect,			TraceGeneric,			0x93},
	{"anda",	2,	DisasmDirect,			TraceGeneric,			0x94},
	{"bita",	2,	DisasmDirect,			TraceGeneric,			0x95},
	{"lda",		2,	DisasmDirect,			TraceGeneric,			0x96},
	{"sta",		2,	DisasmDirect,			TraceGeneric,			0x97},
	{"eora",	2,	DisasmDirect,			TraceGeneric,			0x98},
	{"adca",	2,	DisasmDirect,			TraceGeneric,			0x99},
	{"ora",		2,	DisasmDirect,			TraceGeneric,			0x9a},
	{"adda",	2,	DisasmDirect,			TraceGeneric,			0x9b},
	{"cmpx",	2,	DisasmDirect,			TraceGeneric,			0x9c},
	{"jsr",		2,	DisasmDirect,			TraceGeneric,			0x9d},
	{"ldx",		2,	DisasmDirect,			TraceGeneric,			0x9e},
	{"stx",		2,	DisasmDirect,			TraceGeneric,			0x9f},
	
	{"suba",	2,	DisasmIndexed,			TraceIndexed,			0xa0},
	{"cmpa",	2,	DisasmIndexed,			TraceIndexed,			0xa1},
	{"sbca",	2,	DisasmIndexed,			TraceIndexed,			0xa2},
	{"subd",	2,	DisasmIndexed,			TraceIndexed,			0xa3},
	{"anda",	2,	DisasmIndexed,			TraceIndexed,			0xa4},
	{"bita",	2,	DisasmIndexed,			TraceIndexed,			0xa5},
	{"lda",		2,	DisasmIndexed,			TraceIndexed,			0xa6},
	{"sta",		2,	DisasmIndexed,			TraceIndexed,			0xa7},
	{"eora",	2,	DisasmIndexed,			TraceIndexed,			0xa8},
	{"adca",	2,	DisasmIndexed,			TraceIndexed,			0xa9},
	{"ora",		2,	DisasmIndexed,			TraceIndexed,			0xaa},
	{"adda",	2,	DisasmIndexed,			TraceIndexed,			0xab},
	{"cmpx",	2,	DisasmIndexed,			TraceIndexed,			0xac},
	{"jsr",		2,	DisasmIndexed,			TraceIndexed,			0xad},
	{"ldx",		2,	DisasmIndexed,			TraceIndexed,			0xae},
	{"stx",		2,	DisasmIndexed,			TraceIndexed,			0xaf},
	
	{"suba",	3,	DisasmExtended,			TraceGeneric,			0xb0},
	{"cmpa",	3,	DisasmExtended,			TraceGeneric,			0xb1},
	{"sbca",	3,	DisasmExtended,			TraceGeneric,			0xb2},
	{"subd",	3,	DisasmExtended,			TraceGeneric,			0xb3},
	{"anda",	3,	DisasmExtended,			TraceGeneric,			0xb4},
	{"bita",	3,	DisasmExtended,			TraceGeneric,			0xb5},
	{"lda",		3,	DisasmExtended,			TraceGeneric,			0xb6},
	{"sta",		3,	DisasmExtended,			TraceGeneric,			0xb7},
	{"eora",	3,	DisasmExtended,			TraceGeneric,			0xb8},
	{"adca",	3,	DisasmExtended,			TraceGeneric,			0xb9},
	{"ora",		3,	DisasmExtended,			TraceGeneric,			0xba},
	{"adda",	3,	DisasmExtended,			TraceGeneric,			0xbb},
	{"cmpx",	3,	DisasmExtended,			TraceGeneric,			0xbc},
	{"jsr",		3,	DisasmExtended,			TraceGeneric,			0xbd},
	{"ldx",		3,	DisasmExtended,			TraceGeneric,			0xbe},
	{"stx",		3,	DisasmExtended,			TraceGeneric,			0xbf},
	
	{"subb",	2,	DisasmImmediate,		TraceGeneric,			0xc0},
	{"cmpb",	2,	DisasmImmediate,		TraceGeneric,			0xc1},
	{"sbcb",	2,	DisasmImmediate,		TraceGeneric,			0xc2},
	{"addd",	3,	DisasmImmediateLong,	TraceGeneric,			0xc3},
	{"andb",	2,	DisasmImmediate,		TraceGeneric,			0xc4},
	{"bitb",	2,	DisasmImmediate,		TraceGeneric,			0xc5},
	{"ldb",		2,	DisasmImmediate,		TraceGeneric,			0xc6},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0xc7},
	{"eorb",	2,	DisasmImmediate,		TraceGeneric,			0xc8},
	{"adcb",	2,	DisasmImmediate,		TraceGeneric,			0xc9},
	{"orb",		2,	DisasmImmediate,		TraceGeneric,			0xca},
	{"addb",	2,	DisasmImmediate,		TraceGeneric,			0xcb},
	{"ldd",		3,	DisasmImmediateLong,	TraceGeneric,			0xcc},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0xcd},
	{"ldu",		3,	DisasmImmediateLong,	TraceGeneric,			0xce},
	{NULL,		1,	DisasmIllegal,			TraceGeneric,			0xcf},
	
	{"subb",	2,	DisasmDirect,			TraceGeneric,			0xd0},
	{"cmpb",	2,	DisasmDirect,			TraceGeneric,			0xd1},
	{"sbcb",	2,	DisasmDirect,			TraceGeneric,			0xd2},
	{"addd",	2,	DisasmDirect,			TraceGeneric,			0xd3},
	{"andb",	2,	DisasmDirect,			TraceGeneric,			0xd4},
	{"bitb",	2,	DisasmDirect,			TraceGeneric,			0xd5},
	{"ldb",		2,	DisasmDirect,			TraceGeneric,			0xd6},
	{"stb",		2,	DisasmDirect,			TraceGeneric,			0xd7},
	{"eorb",	2,	DisasmDirect,			TraceGeneric,			0xd8},
	{"adcb",	2,	DisasmDirect,			TraceGeneric,			0xd9},
	{"orb",		2,	DisasmDirect,			TraceGeneric,			0xda},
	{"addb",	2,	DisasmDirect,			TraceGeneric,			0xdb},
	{"ldd",		2,	DisasmDirect,			TraceGeneric,			0xdc},
	{"std",		2,	DisasmDirect,			TraceGeneric,			0xdd},
	{"ldu",		2,	DisasmDirect,			TraceGeneric,			0xde},
	{"stu",		2,	DisasmDirect,			TraceGeneric,			0xdf},
	
	{"subb",	2,	DisasmIndexed,			TraceIndexed,			0xe0},
	{"cmpb",	2,	DisasmIndexed,			TraceIndexed,			0xe1},
	{"sbcb",	2,	DisasmIndexed,			TraceIndexed,			0xe2},
	{"addd",	2,	DisasmIndexed,			TraceIndexed,			0xe3},
	{"andb",	2,	DisasmIndexed,			TraceIndexed,			0xe4},
	{"bitb",	2,	DisasmIndexed,			TraceIndexed,			0xe5},
	{"ldb",		2,	DisasmIndexed,			TraceIndexed,			0xe6},
	{"stb",		2,	DisasmIndexed,			TraceIndexed,			0xe7},
	{"eorb",	2,	DisasmIndexed,			TraceIndexed,			0xe8},
	{"adcb",	2,	DisasmIndexed,			TraceIndexed,			0xe9},
	{"orb",		2,	DisasmIndexed,			TraceIndexed,			0xea},
	{"addb",	2,	DisasmIndexed,			TraceIndexed,			0xeb},
	{"ldd",		2,	DisasmIndexed,			TraceIndexed,			0xec},
	{"std",		2,	DisasmIndexed,			TraceIndexed,			0xed},
	{"ldu",		2,	DisasmIndexed,			TraceIndexed,			0xee},
	{"stu",		2,	DisasmIndexed,			TraceIndexed,			0xef},
	
	{"subb",	3,	DisasmExtended,			TraceGeneric,			0xf0},
	{"cmpb",	3,	DisasmExtended,			TraceGeneric,			0xf1},
	{"sbcb",	3,	DisasmExtended,			TraceGeneric,			0xf2},
	{"addd",	3,	DisasmExtended,			TraceGeneric,			0xf3},
	{"andb",	3,	DisasmExtended,			TraceGeneric,			0xf4},
	{"bitb",	3,	DisasmExtended,			TraceGeneric,			0xf5},
	{"ldb",		3,	DisasmExtended,			TraceGeneric,			0xf6},
	{"stb",		3,	DisasmExtended,			TraceGeneric,			0xf7},
	{"eorb",	3,	DisasmExtended,			TraceGeneric,			0xf8},
	{"adcb",	3,	DisasmExtended,			TraceGeneric,			0xf9},
	{"orb",		3,	DisasmExtended,			TraceGeneric,			0xfa},
	{"addb",	3,	DisasmExtended,			TraceGeneric,			0xfb},
	{"ldd",		3,	DisasmExtended,			TraceGeneric,			0xfc},
	{"std",		3,	DisasmExtended,			TraceGeneric,			0xfd},
	{"ldu",		3,	DisasmExtended,			TraceGeneric,			0xfe},
	{"stu",		3,	DisasmExtended,			TraceGeneric,			0xff},
};

Opcode optable10[]={
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x00},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x01},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x02},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x03},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x04},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x05},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x06},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x07},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x08},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x09},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x0a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x0b},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x0c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x0d},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x0e},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x0f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x10},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x11},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x12},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x13},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x14},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x15},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x16},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x17},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x18},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x19},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x1a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x1b},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x1c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x1d},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x1e},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x1f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x20},
	{"lbrn",	3,	DisasmRelativeLong,		TraceRelativeLong,		0x21},
	{"lbhi",	3,	DisasmRelativeLong,		TraceRelativeLong,		0x22},
	{"lbls",	3,	DisasmRelativeLong,		TraceRelativeLong,		0x23},
	{"lbcc",	3,	DisasmRelativeLong,		TraceRelativeLong,		0x24},
	{"lbcs",	3,	DisasmRelativeLong,		TraceRelativeLong,		0x25},
	{"lbne",	3,	DisasmRelativeLong,		TraceRelativeLong,		0x26},
	{"lbeq",	3,	DisasmRelativeLong,		TraceRelativeLong,		0x27},
	{"lbvc",	3,	DisasmRelativeLong,		TraceRelativeLong,		0x28},
	{"lbvs",	3,	DisasmRelativeLong,		TraceRelativeLong,		0x29},
	{"lbpl",	3,	DisasmRelativeLong,		TraceRelativeLong,		0x2a},
	{"lbmi",	3,	DisasmRelativeLong,		TraceRelativeLong,		0x2b},
	{"lbge",	3,	DisasmRelativeLong,		TraceRelativeLong,		0x2c},
	{"lblt",	3,	DisasmRelativeLong,		TraceRelativeLong,		0x2d},
	{"lbgt",	3,	DisasmRelativeLong,		TraceRelativeLong,		0x2e},
	{"lble",	3,	DisasmRelativeLong,		TraceRelativeLong,		0x2f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x30},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x31},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x32},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x33},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x34},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x35},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x36},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x37},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x38},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x39},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x3a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x3b},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x3c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x3d},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x3e},
	{"os9",		2,	DisasmOS9SysCall,		TraceGeneric,			0x3f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x40},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x41},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x42},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x43},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x44},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x45},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x46},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x47},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x48},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x49},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x4a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x4b},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x4c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x4d},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x4e},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x4f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x50},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x51},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x52},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x53},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x54},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x55},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x56},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x57},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x58},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x59},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x5a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x5b},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x5c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x5d},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x5e},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x5f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x60},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x61},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x62},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x63},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x64},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x65},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x66},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x67},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x68},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x69},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x6a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x6b},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x6c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x6d},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x6e},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x6f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x70},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x71},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x72},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x73},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x74},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x75},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x76},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x77},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x78},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x79},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x7a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x7b},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x7c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x7d},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x7e},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x7f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x80},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x81},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x82},
	{"cmpd",	3,	DisasmImmediateLong,	TraceGeneric,			0x83},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x84},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x85},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x86},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x87},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x88},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x89},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x8a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x8b},
	{"cmpy",	3,	DisasmImmediateLong,	TraceGeneric,			0x8c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x8d},
	{"ldy",		3,	DisasmImmediateLong,	TraceGeneric,			0x8e},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x8f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x90},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x91},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x92},
	{"cmpd",	2,	DisasmDirect,			TraceGeneric,			0x93},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x94},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x95},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x96},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x97},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x98},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x99},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x9a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x9b},
	{"cmpy",	2,	DisasmDirect,			TraceGeneric,			0x9c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x9d},
	{"ldy",		2,	DisasmDirect,			TraceGeneric,			0x9e},
	{"sty",		2,	DisasmDirect,			TraceGeneric,			0x9f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xa0},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xa1},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xa2},
	{"cmpd",	2,	DisasmIndexed,			TraceIndexed,			0xa3},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xa4},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xa5},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xa6},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xa7},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xa8},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xa9},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xaa},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xab},
	{"cmpy",	2,	DisasmIndexed,			TraceIndexed,			0xac},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xad},
	{"ldy",		2,	DisasmIndexed,			TraceIndexed,			0xae},
	{"sty",		2,	DisasmIndexed,			TraceIndexed,			0xaf},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xb0},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xb1},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xb2},
	{"cmpd",	3,	DisasmExtended,			TraceGeneric,			0xb3},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xb4},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xb5},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xb6},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xb7},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xb8},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xb9},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xba},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xbb},
	{"cmpy",	3,	DisasmExtended,			TraceGeneric,			0xbc},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xbd},
	{"ldy",		3,	DisasmExtended,			TraceGeneric,			0xbe},
	{"sty",		3,	DisasmExtended,			TraceGeneric,			0xbf},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc0},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc1},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc2},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc3},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc4},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc5},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc6},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc7},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc8},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc9},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xca},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xcb},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xcc},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xcd},
	{"lds",		3,	DisasmImmediateLong,	TraceGeneric,			0xce},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xcf},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd0},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd1},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd2},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd3},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd4},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd5},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd6},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd7},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd8},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd9},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xda},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xdb},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xdc},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xdd},
	{"lds",		2,	DisasmDirect,			TraceGeneric,			0xde},
	{"sts",		2,	DisasmDirect,			TraceGeneric,			0xdf},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe0},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe1},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe2},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe3},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe4},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe5},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe6},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe7},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe8},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe9},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xea},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xeb},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xec},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xed},
	{"lds",		2,	DisasmIndexed,			TraceIndexed,			0xee},
	{"sts",		2,	DisasmIndexed,			TraceIndexed,			0xef},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf0},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf1},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf2},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf3},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf4},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf5},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf6},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf7},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf8},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf9},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xfa},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xfb},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xfc},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xfd},
	{"lds",		3,	DisasmExtended,			TraceGeneric,			0xfe},
	{"sts",		3,	DisasmExtended,			TraceGeneric,			0xff},
	
};


Opcode optable11[]={
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x00},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x01},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x02},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x03},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x04},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x05},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x06},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x07},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x08},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x09},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x0a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x0b},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x0c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x0d},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x0e},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x0f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x10},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x11},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x12},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x13},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x14},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x15},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x16},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x17},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x18},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x19},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x1a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x1b},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x1c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x1d},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x1e},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x1f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x20},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x21},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x22},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x23},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x24},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x25},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x26},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x27},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x28},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x29},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x2a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x2b},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x2c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x2d},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x2e},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x2f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x30},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x31},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x32},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x33},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x34},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x35},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x36},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x37},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x38},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x39},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x3a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x3b},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x3c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x3d},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x3e},
	{"swi3",	1,	DisasmInherent,			TraceGeneric,			0x3f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x40},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x41},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x42},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x43},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x44},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x45},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x46},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x47},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x48},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x49},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x4a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x4b},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x4c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x4d},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x4e},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x4f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x50},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x51},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x52},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x53},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x54},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x55},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x56},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x57},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x58},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x59},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x5a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x5b},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x5c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x5d},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x5e},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x5f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x60},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x61},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x62},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x63},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x64},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x65},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x66},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x67},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x68},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x69},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x6a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x6b},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x6c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x6d},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x6e},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x6f},
		
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x70},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x71},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x72},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x73},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x74},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x75},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x76},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x77},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x78},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x79},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x7a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x7b},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x7c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x7d},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x7e},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x7f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x80},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x81},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x82},
	{"cmpu",	3,	DisasmImmediateLong,	TraceGeneric,			0x83},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x84},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x85},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x86},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x87},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x88},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x89},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x8a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x8b},
	{"cmps",	3,	DisasmImmediateLong,	TraceGeneric,			0x8c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x8d},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x8e},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x8f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x90},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x91},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x92},
	{"cmpu",	2,	DisasmDirect,			TraceGeneric,			0x93},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x94},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x95},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x96},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x97},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x98},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x99},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x9a},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x9b},
	{"cmps",	2,	DisasmDirect,			TraceGeneric,			0x9c},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x9d},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x9e},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0x9f},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xa0},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xa1},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xa2},
	{"cmpu",	2,	DisasmIndexed,			TraceIndexed,			0xa3},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xa4},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xa5},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xa6},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xa7},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xa8},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xa9},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xaa},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xab},
	{"cmps",	2,	DisasmIndexed,			TraceIndexed,			0xac},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xad},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xae},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xaf},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xb0},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xb1},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xb2},
	{"cmpu",	3,	DisasmExtended,			TraceGeneric,			0xb3},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xb4},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xb5},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xb6},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xb7},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xb8},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xb9},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xba},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xbb},
	{"cmps",	3,	DisasmExtended,			TraceGeneric,			0xbc},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xbd},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xbe},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xbf},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc0},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc1},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc2},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc3},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc4},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc5},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc6},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc7},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc8},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xc9},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xca},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xcb},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xcc},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xcd},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xce},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xcf},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd0},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd1},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd2},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd3},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd4},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd5},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd6},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd7},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd8},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xd9},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xda},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xdb},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xdc},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xdd},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xde},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xdf},
	
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe0},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe1},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe2},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe3},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe4},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe5},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe6},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe7},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe8},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xe9},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xea},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xeb},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xec},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xed},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xee},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xef},
		
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf0},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf1},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf2},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf3},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf4},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf5},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf6},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf7},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf8},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xf9},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xfa},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xfb},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xfc},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xfd},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xfe},
	{NULL,		0,	DisasmIllegal,			TraceGeneric,			0xff},
};



/*****************************************************************************
	
	Copyright (C) 1996, 1997, 2014, 2018, by Chet Simpson
	
	Permission is hereby granted, free of charge, to any person
	obtaining a copy of this software and associated documentation
	files (the "Software"), to deal in the Software without
	restriction, including without limitation the rights to use,
	copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the
	Software is furnished to do so, subject to the following
	conditions:
	
	The above copyright notice and this permission notice shall be
	included in all copies or substantial portions of the Software.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
	EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
	OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
	NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
	HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
	WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
	FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
	OTHER DEALINGS IN THE SOFTWARE.
	
*****************************************************************************/
